inherit_from:
  - ./rubocop.yml
  - ./rubocop-capybara.yml
  - ./rubocop-factory_bot.yml
  - ./rubocop-performance.yml
  - ./rubocop-rails.yml
  - ./rubocop-rake.yml
  - ./rubocop-rspec.yml
  - ./rubocop-rspec_rails.yml

inherit_mode:
  merge:
    - Exclude
    - Include

AllCops:
  ActiveSupportExtensionsEnabled: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
