# Automatic Rails code style checking tool. A RuboCop extension focused on
# enforcing Rails best practices and coding conventions.
#
# @see https://rubygems.org/gems/rubocop-rails
# @see https://docs.rubocop.org/rubocop-rails
# @see https://github.com/rubocop/rubocop-rails

plugins: rubocop-rails

Rails/DefaultScope:
  Enabled: true

Rails/EnvironmentVariableAccess:
  Enabled: true
  AllowReads: true

Rails/OrderById:
  Enabled: true

Rails/PluckId:
  Enabled: true

Rails/RequireDependency:
  Enabled: true

Rails/ReversibleMigrationMethodDefinition:
  Enabled: true

Rails/SaveBang:
  Enabled: true
  AllowImplicitReturn: false

Rails/TableNameAssignment:
  Enabled: true
