# Style cops check for stylistic consistency of your code. Many of the them are
# based on the Ruby Style Guide.
#
# @see https://docs.rubocop.org/rubocop/cops_style.html

Style/ArrayCoercion:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/ClassMethodsDefinitions:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/DateTime:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MultilineMethodSignature:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/Send:
  Enabled: true

Style/StaticClass:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/UnlessLogicalOperators:
  Enabled: true
